// Cloudflare Workers deployment (T-248, ADR-032): the vinext build of this app runs as the
// `modern-lms` Worker. Generated by `vinext init --platform=cloudflare` with no CDN/data cache
// (personalised, signed-in pages must never be served from a shared cache).
import { bindings, defineConfig, defineWorker } from "cf/config";

export default defineConfig({
  worker: defineWorker({
    name: "modern-lms",
    entrypoint: "vinext/server/fetch-handler",
    compatibilityDate: "2026-10-01",
    compatibilityFlags: ["nodejs_compat"],
    assets: { notFoundHandling: "none" },
    env: {
      ASSETS: bindings.assets(),
      // Server-only secret (ADR-032). Set it in the Worker's Settings → Variables and secrets;
      // locally it comes from .dev.vars (gitignored). Never a plain variable.
      SUPABASE_SERVICE_ROLE_KEY: bindings.secret(),
    },
  }),
});
